#默认使用配置
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zdr.springcloud.tickerserver.entity
  mapperLocations: classpath*:com/zdr/springcloud/tickerserver/mapper/*.xml


---

#开发配置
spring:
  profiles: dev
  application:
    name: cloud-provider-ticket
  main:
    allow-bean-definition-overriding: true

#  datasource:
#    url: jdbc:oracle:thin:@192.168.31.96:1521/xe
#    username: sbfpdata
#    password: sbfpdata#    driver-class-name: oracle.jdbc.driver.OracleDriver

logging:
  path: /logs
  level:
    root: INFO
    org.springframework.web: error
    org.springframework.test: info

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.96:8500/eureka
