#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:oracle:thin:@192.168.31.96:1521/xe
    username: sbfpdata
    password: sbfpdata
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: cloud-provider-user
  main:
    allow-bean-definition-overriding: true
  redis:
    password:
    database: 0
    port: 6379
    jedis:
      pool:
        max-idle: 200
        min-idle: 0
        max-active: 1024
        max-wait: 10000ms
    host: 192.168.31.96
    timeout: 10000ms
    block-when-exhausted: true


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zdr.springcloud.userserver.entity
  mapperLocations: classpath*:com/zdr/springcloud/userserver/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

#mybatis-plus
mybatis-plus:
  type-aliases-package: com.zdr.springcloud.userserver.entity
  mapper-locations: classpath*:com/zdr/springcloud/userserver/mapper/*.xml

logging:
  path: G:\\IDEA2017Projects\\spring-cloud-learning\\tickerserver\\logs
  level:
    root: INFO
    org.springframework.web: error
    org.springframework.test: info
server:
  port: 8000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka

