#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:oracle:thin:@192.168.31.96:1521/xe
    username: sbfpdata
    password: sbfpdata
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
    name: cloud-provider-user
  main:
    allow-bean-definition-overriding: true
  server:
    port: 8989
  redis:
    host: 192.168.31.96
    port: 6379
    # 密码 没有则可以不填
    password:
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zdr.springcloud.userserver.entity
  mapperLocations: classpath*:com/zdr/springcloud/userserver/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

#mybatis-plus
mybatis-plus:
  type-aliases-package: com.zdr.springcloud.userserver.entity
  mapper-locations: classpath*:com/zdr/springcloud/userserver/mapper/*.xml

logging:
  path: G:\\IDEA2017Projects\\spring-cloud-learning\\tickerserver\\logs
  level:
    root: info
    org.springframework.web: error
    org.springframework.test: info
server:
  port: 8000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka

