spring:
  application:
    name: springcloud_eurekaserver
---
spring:
  profiles: eurekaserver1
server:
  port: 8500
eureka:
  instance:
    hostname: eurekaserver1
  client:
#    registerWithEureka: false  #是否将自己注册到Eureka Server,默认true
#    fetchRegistry: false       #是否从Eureka Server获取注册信息，默认true
    serviceUrl:
      defaultZone: http://eurekaserver2:8501/eureka   #与Eureka Server交互的地址，查询、注册服务关联此地址

---
spring:
  profiles: eurekaserver2
server:
  port: 8501
eureka:
  instance:
    hostname: eurekaserver2
  client:
    #    registerWithEureka: false  #是否将自己注册到Eureka Server,默认true
    #    fetchRegistry: false       #是否从Eureka Server获取注册信息，默认true
    serviceUrl:
      defaultZone: http://eurekaserver1:8500/eureka   #与Eureka Server交互的地址，查询、注册服务关联此地址
