#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://106.54.229.27:3306/mysql?useUnicode=true&useSSL=true
    username: root
    password: bank1234
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: cloud-provider-user
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 106.54.229.27
#    host: 192.168.31.96
    port: 6379
    # 密码 没有则可以不填
    password:
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 16
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 1
        max-wait: -1ms


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.zdr.springcloud.userserver.entity
  mapperLocations: classpath*:com/zdr/springcloud/userserver/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

#mybatis-plus
mybatis-plus:
  type-aliases-package: com.zdr.springcloud.userserver.entity
  mapper-locations: classpath*:com/zdr/springcloud/userserver/mapper/*.xml

logging:
  path: /logs
  level:
    root: info
    org.springframework.web: error
    org.springframework.test: info
    com:
      zdr:
        springcloud:
          userserver:
            repositry: debug
server:
  port: 8000


eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.96:8500/eureka

